Structura general.
Banneeddm/spotify-service pull request #1
Opened 2021-11-04 14:50 UTC by Banneeddm

Estructura general del proyecto casi lista.

2021-11-05 14:42 UTC, mrojasabregu requested changes
porfa agregar en los gitignore 

.idea
.mvn
target/

y borra esos archivos del commit para que no salgan nuevamente

2021-11-05 14:42 UTC, mrojasabregu commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
borrate los archivos .idea, 

no se suben esta carpeta ni los /target

2021-11-05 14:42 UTC, mrojasabregu commented on spotify-service/.mvn/wrapper/MavenWrapperDownloader.java
> +                protected PasswordAuthentication getPasswordAuthentication() {
los .mvn tampoco lo subimos

2021-11-05 14:42 UTC, mrojasabregu commented on spotify-service/pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
1.0.0

2021-11-05 14:42 UTC, mrojasabregu commented on spotify-service/pom.xml
> +	<description>Demo project for Spring Boot - spotify-service</description>
cambiar la descripción

2021-11-05 15:20 UTC, maalbera commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
agregar al gitignore

2021-11-05 15:20 UTC, maalbera commented on .idea/.gitignore
> +# Default ignored files
Editar el gitignore:

HELP.md
target/
!.mvn/wrapper/maven-wrapper.jar
!**/src/main/**/target/
!**/src/test/**/target/

### STS ###
.apt_generated
.classpath
.factorypath
.project
.settings
.springBeans
.sts4-cache

### IntelliJ IDEA ###
.idea
*.iws
*.iml
*.ipr

### NetBeans ###
/nbproject/private/
/nbbuild/
/dist/
/nbdist/
/.nb-gradle/
build/
!**/src/main/**/build/
!**/src/test/**/build/

### VS Code ###
.vscode/

2021-11-05 15:20 UTC, maalbera commented on spotify-service/src/main/java/com/spotifyservice/spotifyservice/domain/Track.java
> +    private Long idArtist;
Usar Objeto Artist en vez de int.

2021-11-05 15:20 UTC, maalbera commented on spotify-service/src/main/java/com/spotifyservice/spotifyservice/domain/Track.java
> -    private int idAlbum;
Usar Objeto Album en vez de int

2021-11-05 15:20 UTC, maalbera commented on spotify-service/src/main/java/com/spotifyservice/spotifyservice/configuration/TrackConfiguration.java
> +    @Bean(name = "/{idTrack}")
al bean le pusiste no nombre "/{idTrack}"
No esta mal. Pero se presta a confusión, lo podrías tomar a simple vista como una URL

2021-11-05 15:20 UTC, maalbera commented on spotify-service/src/main/java/com/spotifyservice/spotifyservice/domain/Track.java
> -    private int idArtist;
Usar objeto Artist en vez de int

2021-11-05 15:20 UTC, maalbera commented on spotify-service/src/main/java/com/spotifyservice/spotifyservice/service/ArtistService.java
>          return artistMapper.apply(artistRequest);
deberias guardar el artista en una lista o un map, para despues poder hacer la edicion y el borrado

2021-11-08 16:13 UTC, maalbera approved these changes

2021-11-08 16:57 UTC, merged